version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: 'Run Jest and Collect Coverage Reports'
          command: npm run test:coverage
      - store_artifacts:
          path: coverage
      - run:
          name: 'Report coverage to coveralls'
          command: npm run coveralls
